M48
; DRILL file {KiCad 8.0.2} date 2024-05-19T19:48:27-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-19T19:48:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X2.8862Y-3.7776
X3.1138Y-3.7776
T2
X2.1376Y-3.6537
X3.0Y-2.16
X3.8624Y-3.6537
M30
